version: '3.8'

services:
  php:
    build: 
      context: ./src/docker
      dockerfile: Dockerfile    
    ports:
      - "${PHP_PORT:-80}:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - lex-network

  mysql:
    image: mysql:8.0
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-project_db}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - lex-network

networks:
  lex-network:
    driver: bridge

volumes:
  mysql-data:
